/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "MSA_server.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(request_uniqe_number, request_uniqe_number, AUTO)


PB_BIND(request_Temp, request_Temp, AUTO)


PB_BIND(coordinates, coordinates, AUTO)


PB_BIND(request_GPS, request_GPS, AUTO)


