/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MSA_SERVER_PB_H_INCLUDED
#define PB_MSA_SERVER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _request_uniqe_number {
    uint64_t Index;
    int64_t number;
} request_uniqe_number;

typedef struct _request_Temp {
    uint64_t Index;
    float temp;
} request_Temp;

typedef struct _coordinates {
    pb_callback_t side;
    float minutes;
    float ouers;
} coordinates;

typedef struct _request_GPS {
    int64_t Index;
    bool IsVisebleSputnik;
    int64_t minutes;
    int64_t hours;
    pb_callback_t longitude;
    pb_callback_t latitude;
} request_GPS;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define request_uniqe_number_init_default        {0ull, 0}
#define request_Temp_init_default                {1ull, 0}
#define coordinates_init_default                 {{{NULL}, NULL}, 0, 0}
#define request_GPS_init_default                 {2ll, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define request_uniqe_number_init_zero           {0, 0}
#define request_Temp_init_zero                   {0, 0}
#define coordinates_init_zero                    {{{NULL}, NULL}, 0, 0}
#define request_GPS_init_zero                    {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define request_uniqe_number_Index_tag           1
#define request_uniqe_number_number_tag          2
#define request_Temp_Index_tag                   1
#define request_Temp_temp_tag                    2
#define coordinates_side_tag                     1
#define coordinates_minutes_tag                  2
#define coordinates_ouers_tag                    3
#define request_GPS_Index_tag                    1
#define request_GPS_IsVisebleSputnik_tag         2
#define request_GPS_minutes_tag                  3
#define request_GPS_hours_tag                    4
#define request_GPS_longitude_tag                5
#define request_GPS_latitude_tag                 6

/* Struct field encoding specification for nanopb */
#define request_uniqe_number_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   Index,             1) \
X(a, STATIC,   REQUIRED, INT64,    number,            2)
#define request_uniqe_number_CALLBACK NULL
#define request_uniqe_number_DEFAULT (const pb_byte_t*)"\x08\x00\x00"

#define request_Temp_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   Index,             1) \
X(a, STATIC,   REQUIRED, FLOAT,    temp,              2)
#define request_Temp_CALLBACK NULL
#define request_Temp_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define coordinates_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   side,              1) \
X(a, STATIC,   REQUIRED, FLOAT,    minutes,           2) \
X(a, STATIC,   REQUIRED, FLOAT,    ouers,             3)
#define coordinates_CALLBACK pb_default_field_callback
#define coordinates_DEFAULT NULL

#define request_GPS_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    Index,             1) \
X(a, STATIC,   REQUIRED, BOOL,     IsVisebleSputnik,   2) \
X(a, STATIC,   REQUIRED, INT64,    minutes,           3) \
X(a, STATIC,   REQUIRED, INT64,    hours,             4) \
X(a, CALLBACK, REPEATED, MESSAGE,  longitude,         5) \
X(a, CALLBACK, REPEATED, MESSAGE,  latitude,          6)
#define request_GPS_CALLBACK pb_default_field_callback
#define request_GPS_DEFAULT (const pb_byte_t*)"\x08\x02\x00"
#define request_GPS_longitude_MSGTYPE coordinates
#define request_GPS_latitude_MSGTYPE coordinates

extern const pb_msgdesc_t request_uniqe_number_msg;
extern const pb_msgdesc_t request_Temp_msg;
extern const pb_msgdesc_t coordinates_msg;
extern const pb_msgdesc_t request_GPS_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define request_uniqe_number_fields &request_uniqe_number_msg
#define request_Temp_fields &request_Temp_msg
#define coordinates_fields &coordinates_msg
#define request_GPS_fields &request_GPS_msg

/* Maximum encoded size of messages (where known) */
/* coordinates_size depends on runtime parameters */
/* request_GPS_size depends on runtime parameters */
#define MSA_SERVER_PB_H_MAX_SIZE                 request_uniqe_number_size
#define request_Temp_size                        16
#define request_uniqe_number_size                22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
